---
# tasks file for win_ad_install
- name: install ad-domain-services
  win_feature:
    name: ad-domain-services
    state: present

- name: set up ad controller
  win_domain:
    dns_domain_name: "{{ ssh_host }}"
    safe_mode_password: "{{ ansible_password }}"

- name: reboot instance
  win_reboot:
    reboot_timeout: "600"

- name: list domain
  win_shell: nltest /dclist:"{{ ad_domain_name }}"