- name: setup win ssh server
  hosts: windows
  tasks:
  - name: Bare include (free-form)
    include_vars: ./ssh_var.yml
  - name: run win win_service_config
    include_role: 
      name: win_service_config